CVP_CONFIGLETS:


CVP_DEVICES:
  leaf1-DC1:
    name: 'leaf1-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'leaf1-DC1-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  leaf2-DC1:
    name: 'leaf2-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'leaf2-DC1-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported  
  leaf3-DC1:
    name: 'leaf3-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'leaf3-DC1-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  leaf4-DC1:
    name: 'leaf4-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'leaf4-DC1-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported
  borderleaf1-DC1:
    name: 'borderleaf1-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'borderleaf1-DC1-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  borderleaf2-DC1:
    name: 'borderleaf2-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'borderleaf2-DC1-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported      
  spine1-DC1:
    name: 'spine1-DC1'
    parentContainerName: Spine-DC1
    configlets:
        - 'ATD-INFRA'
        - 'spine1-DC1-BASE'
    imageBundle: []  # Not yet supported  
  spine2-DC1:
    name: 'spine2-DC1'
    parentContainerName: Spine-DC1
    configlets:
        - 'ATD-INFRA'
        - 'spine2-DC1-BASE'
    imageBundle: []  # Not yet supported  
  spine3-DC1:
    name: 'spine3-DC1'
    parentContainerName: Spine-DC1
    configlets:
        - 'ATD-INFRA'
        - 'spine3-DC1-BASE'
    imageBundle: []  # Not yet supported
  leaf1-DC2:
    name: 'leaf1-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf1-DC2-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  leaf2-DC2:
    name: 'leaf2-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf2-DC2-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported  
  leaf3-DC2:
    name: 'leaf3-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf3-DC2-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  leaf4-DC2:
    name: 'leaf4-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf4-DC2-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported
  borderleaf1-DC2:
    name: 'borderleaf1-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'borderleaf1-DC2-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  borderleaf2-DC2:
    name: 'borderleaf2-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'borderleaf2-DC2-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported      
  spine1-DC2:
    name: 'spine1-DC2'
    parentContainerName: Spine-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf1-DC2-BASE'
    imageBundle: []  # Not yet supported  
  spine2-DC2:
    name: 'spine2-DC2'
    parentContainerName: Spine-DC2
    configlets:
        - 'ATD-INFRA'
        - 'spine2-DC2-BASE'
    imageBundle: []  # Not yet supported  
  spine3-DC2:
    name: 'spine3-DC2'
    parentContainerName: Spine-DC2
    configlets:
        - 'ATD-INFRA'
        - 'spine3-DC2-BASE'
    imageBundle: []  # Not yet supported  
  DCI:
    name: 'DCI'
    parentContainerName: DCI
    configlets:
        - 'ATD-INFRA'
        - 'DCI-BASE'
    imageBundle: []  # Not yet supported  
  core1-ISP1:
    name: 'core1-ISP1'
    parentContainerName: ISP1
    configlets:
        - 'ATD-INFRA'
        - 'core1-ISP1-BASE'
    imageBundle: []  # Not yet supported  
  core2-ISP1:
    name: 'core2-ISP1'
    parentContainerName: ISP1
    configlets:
        - 'ATD-INFRA'
        - 'core2-ISP1-BASE'
    imageBundle: []  # Not yet supported  
  core1-ISP2:
    name: 'core1-ISP2'
    parentContainerName: ISP2
    configlets:
        - 'ATD-INFRA'
        - 'core1-ISP2-BASE'
    imageBundle: []  # Not yet supported  
  core2-ISP2:
    name: 'core2-ISP2'
    parentContainerName: ISP2
    configlets:
        - 'ATD-INFRA'
        - 'core2-ISP2-BASE'
    imageBundle: []  # Not yet supported  
  OOB-CORE:
    name: 'OOB-CORE'
    parentContainerName: OOB
    configlets:
        - 'ATD-INFRA'
        - 'OOB-CORE-BASE'
    imageBundle: []  # Not yet supported
  OOB-DC1:
    name: 'OOB-DC1'
    parentContainerName: OOB
    configlets:
        - 'ATD-INFRA'
        - 'OOB-DC1-BASE'
    imageBundle: []  # Not yet supported  
  OOB-DC2:
    name: 'OOB-DC2'
    parentContainerName: OOB
    configlets:
        - 'ATD-INFRA'
        - 'OOB-DC2-BASE'
    imageBundle: []  # Not yet supported
  internet:
    name: 'internet'
    parentContainerName: Internet
    configlets:
        - 'ATD-INFRA'
        - 'internet-BASE'
    imageBundle: []  # Not yet supported 
  host1-DC3:
    name: 'host1-DC3'
    parentContainerName: Host-DC3
    configlets:
        - 'ATD-INFRA'
        - 'host1-DC3-BASE'
    imageBundle: []  # Not yet supported
  SW1-DC3:
    name: 'SW1-DC3'
    parentContainerName: SW-DC3
    configlets:
        - 'ATD-INFRA'
        - 'SW1-DC3-BASE'
    imageBundle: []  # Not yet supported
  cvx:
    name: 'cvx'
    parentContainerName: CVX
    configlets:
        - 'ATD-INFRA'
        - 'CVX-BASE'
    imageBundle: []  # Not yet supported
  host1-DC1:
    name: 'host1-DC1'
    parentContainerName: Host-DC1
    configlets:
        - 'ATD-INFRA'
        - 'host1-DC1-BASE'
    imageBundle: []  # Not yet supported
  host2-DC1:
    name: 'host2-DC1'
    parentContainerName: Host-DC1
    configlets:
        - 'ATD-INFRA'
        - 'host2-DC1-BASE'
    imageBundle: []  # Not yet supported    
  host1-DC2:
    name: 'host1-DC2'
    parentContainerName: Host-DC2
    configlets:
        - 'ATD-INFRA'
        - 'host1-DC2-BASE'
    imageBundle: []  # Not yet supported
  host2-DC2:
    name: 'host2-DC2'
    parentContainerName: Host-DC2
    configlets:
        - 'ATD-INFRA'
        - 'host2-DC2-BASE'
    imageBundle: []  # Not yet supported    