---
- name: Reset Lab Environment
  hosts: CloudVision
  connection: local
  gather_facts: no

  tasks:
  
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: CVP_FACTS

    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device:
        devices: "{{CVP_DEVICES}}"
        cvp_facts: '{{CVP_FACTS.ansible_facts}}'
        state: present
      register: CVP_DEVICES_RESULTS
